### ISSUE TITLE
[OLD_BUG]: INVALID_ARGUMENT invalid address(argument="address") | Error thrown at sending transaction via smart contract method

### ISSUE THREAD

**Issue by gouravkhator** [gouravkhator/stran#2]
> **Note: This was an old bug. It is been fixed, but just to keep here for archival purposes.**

## Describe the bug

If we pass just the javascript number type in the params of a smart contract method like registerUser.
And we know, that registerUser in smart contract also takes uint8, then we need to parse the number using parseInt.

Why there was an issue if we didn't do an extra parsing step??
> It maybe bcoz web3 is parsing the javascript number again to string, and solidity wants that param to be uint8.
That is why we are getting below error like INVALID_ARGUMENT.

## To Reproduce
1. If parseInt is not used while calling smart contract methods, then run the localnode of blockchain.
2. And then run the deploy contract script.
3. Then run `node smart-contract.service.js`

## Environment
 - NodeJS v16.13.0

## Error Stack Trace

```sh
 /home/gourav/Documents/other_repos/stran/server/node_modules/@ethersproject/logger/lib/index.js:199
            var error = new Error(message);
                        ^

    Error: invalid address (argument="address", value={"transactionHash":"0x3d09a7dad4c106d8cc5e2a6ece8636585e747d88f2d638cc16196a8bb6272731","transactionIndex":0,"
        .....

        at AddressCoder.Coder._throwError (/home/gourav/Documents/other_repos/stran/server/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:40:16)
        at AddressCoder.encode (/home/gourav/Documents/other_repos/stran/server/node_modules/@ethersproject/abi/lib/coders/address.js:29:18)
        at /home/gourav/Documents/other_repos/stran/server/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
        at Array.forEach (<anonymous>)
        at Object.pack (/home/gourav/Documents/other_repos/stran/server/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
```

## Resolution

Edit the method calling in smart-contract.service.js like the following code:

```js
const transactionObj = await vcContract.methods.registerUser(
    name,
    parseInt(currentLocation),
    parseInt(primaryLanguage),
    knownLanguages.map((val) => parseInt(val))
).send({
    from: accounts[0],
});
```

**Check [this](https://ethereum.stackexchange.com/questions/19524/invalid-address-error-when-interacting-with-a-smart-contract-with-metamask) for more reference.**

**Comment by gouravkhator** [comment]
This bug is fixed in [this](https://github.com/gouravkhator/stran/commit/efc08226b83dd1a0a0f4325739ef9983cadc31da) commit. 
The resolution is same as what is added in the issue resolution tips.
